<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_AdvancedReviews
 * @version    2.3.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php
?>
<?php if ( $this->canShow() ):  ?>
            <table class="product-review-table" cellspacing="0">
                <tbody>
                    <tr>
                        <th><?php echo $this->__('Pros') ?></th>
                    </tr>
                    <tr>
                        <td>
<!-- Pros -->
    <ul class="pro-con-list form-list">
    <?php if ( $pros = $this->getProsCollection() ):  ?>
        <?php if ( count($pros) ):  ?>
            <?php $i=0;?>
            <?php foreach( $pros as $prosItem ): ?>
                <li class="control">
                    <input name="proscons_items[]" id="props-<?php echo $prosItem->getId() ?>" value="<?php echo $prosItem->getId() ?>" type="checkbox">
                    <label for="props-<?php echo $prosItem->getId() ?>"><?php echo $this->__( $prosItem->getName() ) ?></label>
                </li>
            <?php $i++;?>
            <?php endforeach ?>
            
            <?php if($i>Mage::helper('advancedreviews')->confProsDisplayCount()):?>
                <li>
                    <a href="#" onclick="showHideProscons('pros',true);return false;" id="hiddenProsListSwitcher_form"><?php echo $this->__( 'show more Pros' ) ?></a>
                </li>
            <?php endif;?>
        <?php endif ?>
    <?php endif ?>
    <?php if ( $this->showUserDefined() ): ?>
        <li class="pro-con-custom">
            <label><?php echo  $this->__('Enter your Pros, separated by comma') ?></label>
            <div class="input-box">
                <input type="text" name="user-pros" value="" class="input-text" />
            </div>
        </li>
    <?php endif ?>
        </ul>
    </td>
  </tr>
    <tr>
        <th><?php echo $this->__('Cons') ?></th>
    </tr>
  <tr>
    <td>
<!-- Cons -->
           <ul class="pro-con-list form-list">

    <?php if ( $cons = $this->getConsCollection() ):  ?>
        <?php if ( count($cons) ):  ?>
            <?php $i=0;?>
            <?php foreach( $cons as $consItem ): ?>
                <li class="control">
                    <input name="proscons_items[]" id="conss-<?php echo $consItem->getId() ?>" value="<?php echo $consItem->getId() ?>" type="checkbox">
                    <label for="conss-<?php echo $consItem->getId() ?>"><?php echo $this->__( $consItem->getName() ) ?></label>
                </li>
            <?php $i++;?>
            <?php endforeach ?>

            <?php if($i>Mage::helper('advancedreviews')->confConsDisplayCount()):?>
                <li>
                    <a href="#" onclick="showHideProscons('cons',true);return false;" id="hiddenConsListSwitcher_form"><?php echo $this->__('show more Cons') ?></a>
                </li>
            <?php endif;?>
        <?php endif ?>
    <?php endif ?>
    <?php if ( $this->showUserDefined() ): ?>
        <li class="pro-con-custom">
            <label><?php echo  $this->__('Enter your Cons, separated by comma') ?></label>
            <div class="input-box">
                <input type="text" name="user-cons" value="" class="input-text" />
            </div>
        </li>
    <?php endif ?>
            </ul>
                        </td>
                    </tr>
                </tbody>
            </table>
<?php endif ?>