<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_AdvancedReviews
 * @version    2.3.2
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php if(Mage::helper('advancedreviews')->getSummaryBlockEnabled() && is_array($this->getSummaryBlock())):?>
<?php if(count($this->getSummaryBlock())):?>
<div class="advancedreviews-summary-block">
    <?php foreach($this->getSummaryBlock() as $parametr):?>
        <?php if($parametr['votes_qty'] > 0): ?>
            <div class="review-snapshot">
                <h3><?php echo $this->__('Review Snapshot'); ?></h3>
                    <ul class="review-breakdown">
                    <?php foreach($parametr['votes'] as $mark=>$qty): ?>
                        <li>
                            <?php echo $mark; ?> star:
                            <span class="rating">
                                <div class="rating-box">
                                    <div class="rating" style="width:<?php echo $qty['percent'] ?>%;"></div>
                                </div>
                            </span>
                            <?php echo $qty['qty']; ?>
                        </li>
                    <?php endforeach; ?>
                    </ul>
            </div>
            <div class="average-customer-review">
                <h3><?php echo $this->__('Average Customer Review'); ?></h3>
                <p>
                    <?php $plural = ($parametr['votes_qty'] > 1) ? 's' : ''; ?>
                    <?php echo $this->__('<strong>%s</strong> average rating from <strong>%s</strong> customer review%s', $this->getAverageStarRating($parametr['votes']), $parametr['votes_qty'], $plural) ?>
                </p>
            </div>
        <?php endif; ?>
    <?php endforeach;?>
    <div class="spacer"></div>
</div>
<?php endif;?>
<?php endif;?>