<div class="section active allow">
  <div class="step-title">
    <h2><?php echo $this->__('Shop With Confidence'); ?></h2>
  </div>
  <div class="security-images clearer">

    <img src="<?php echo $this->getSkinUrl('images/gia-certified.png'); ?>" alt="<?php echo $this->__('GIA Certified'); ?>" class="gia-certified-badge">
    <img class="norton-secured-badge" src="<?php echo $this->getSkinUrl('images/norton-secured.png'); ?>" alt="<?php echo $this->__('Norton Secured'); ?>">
    <img class="bizrate-badge" src="<?php echo $this->getSkinUrl('images/biz-rate.png'); ?>" alt="<?php echo $this->__('BizRate'); ?>">
  </div>
</div>