<div class="block block-account">
    <div class="block-title">
        <strong><span><?php echo $this->__('My Account'); ?></span></strong>
    </div>
    <div class="block-content">
        <ul>
            <?php
            $_links      = $this->getLinks();
            $_index      = 1;
            $_count      = count($_links);
            $_baseURL    = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB);
            $_currentURL = "";

            // TODO: Remove links listed below via layout XMLs
            $_denyLinks = array(
                // My Downloadable Products
                "/downloadable/customer/products/",
                // My Tags
                "/tag/customer/",
                // My Applications
                "/oauth/customer_token/",
                // Recurring Profiles
                "/sales/recurring_profile/",
                // Billing Agreements
                "/sales/billing_agreement/"
            );
            ?>
            <?php foreach ($_links as $_link): ?>
                <?php $_currentURL = str_replace($_baseURL, "/", $_link->getUrl()); ?>
                <?php $_last = ($_index++ >= $_count); ?>
                <?php if (!in_array($_currentURL, $_denyLinks)) : ?>
                <?php if ($this->isActive($_link)): ?>
                    <li class="current<?php echo ($_last ? ' last' : '') ?>"><strong><?php echo $_link->getLabel() ?></strong></li>
                    <?php else: ?>
                    <li<?php echo ($_last ? ' class="last"' : '') ?>><a href="<?php echo $_link->getUrl() ?>"><?php echo $_link->getLabel() ?></a></li>
                    <?php endif; ?>
                <?php endif ?>
            <?php endforeach; ?>
        </ul>
    </div>
</div>
