<!-- Google Code for Order Conversion Page -->
<script type="text/javascript">
    /* <![CDATA[ */
    var google_conversion_id = 997525034;
    var google_conversion_language = "en";
    var google_conversion_format = "3";
    var google_conversion_color = "ffffff";
    var google_conversion_label = "LYp9CI7OigQQqozU2wM";
    var google_conversion_value = 0;
    /* ]]> */
</script>
<script type="text/javascript" src="https://www.googleadservices.com/pagead/conversion.js">
</script>
<noscript>
    <div style="display:inline;">
        <img height="1" width="1" style="border-style:none;" alt="" src="https://www.googleadservices.com/pagead/conversion/997525034/?value=0&label=LYp9CI7OigQQqozU2wM&guid=ON&script=0"/>
    </div>
</noscript>

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<?php if ($this->getOrderId()):?>
    <?php
    $_order = Mage::getModel('sales/order')->loadByIncrementId($this->getOrderId()); 
    ?>
    <?php if($_order->getCustomerIsGuest()): ?>
        <?php echo $this->getChild('success.newaccount.form')
                ->setData('order', $_order)->toHtml(); ?>
    <?php endif; ?>
    <?php echo $this->getChild('success.order.info')
        ->setData('order', $_order)->toHtml(); ?>
    <?php echo $this->getChild('success.cart.items')
        ->setData('order', $_order)->toHtml(); ?>
<?php endif;?>

<?php if ($this->getAgreementRefId()): ?>
    <p><?php echo $this->__('Your billing agreement # is: %s.', sprintf('<a href="%s">%s</a>', $this->escapeHtml($this->getAgreementUrl()), $this->escapeHtml($this->getAgreementRefId())))?></p>
<?php endif;?>

<?php if ($profiles = $this->getRecurringProfiles()):?>
<p><?php echo $this->__('Your recurring payment profiles:'); ?></p>
<ul class="disc">
<?php foreach($profiles as $profile):?>
<?php $profileIdHtml = ($this->getCanViewProfiles() ? sprintf('<a href="%s">%s</a>', $this->escapeHtml($this->getProfileUrl($profile)), $this->escapeHtml($this->getObjectData($profile, 'reference_id'))) : $this->escapeHtml($this->getObjectData($profile, 'reference_id')));?>
    <li><?php echo $this->__('Payment profile # %s: "%s".', $profileIdHtml, $this->escapeHtml($this->getObjectData($profile, 'schedule_description')))?></li>
<?php endforeach;?>
</ul>
<?php endif;?>

<div class="buttons-set">
    <?php if ($this->getCanViewOrder() && $this->getCanPrintOrder()) :?>
        <a href="<?php echo $this->getPrintUrl(); ?>" class="button">
            <span><?php echo $this->__('Print Receipt'); ?></span>
        </a>
    <?php endif;?>
    <a href="<?php echo $this->getUrl(); ?>" class="button primary-button" title="<?php echo $this->__('Continue Shopping'); ?>">
        <span><?php echo $this->__('Continue Shopping'); ?></span>
    </a>
</div>
