<div class="footer-additional">
    <?php echo $this->getChildHtml("bottomContainer") ?>
</div>
<div class="footer-container">
    <div class="footer">
        <div class="why-shop-ice">
            <?php echo $this->getChildHtml("cms_footer_why_shop_ice") ?>
        </div>
        <div class="service">
            <?php echo $this->getChildHtml("cms_footer_links") ?>
            <?php echo $this->getChildHtml("footer_links") ?>
        </div>
        <div class="newsletter-form">
            <?php echo $this->getChildHtml("newsletter") ?>
            <?php echo $this->getChildHtml("cms_footer_social_buttons") ?>
        </div>
    </div>
    <ul class="sub-footer">
        <li><?php echo $this->getChildHtml("cms_footer_banners") ?></li>
        <li><?php echo str_replace('{{current_year}}', date('Y'), $this->getChildHtml("cms_footer_copyright_and_terms")) ?></li>
    </ul>
</div>

<?php echo $this->getChildHtml("newsletter_popup") ?>