<?php
/**
 * Top menu for store
 *
 * @var $this Mage_Page_Block_Html_Topmenu
 */
?>
<?php $_menu = $this->getHtml('level-top', 'block-menu-wrapper') ?>
<?php if($_menu): ?>
<div class="menu-preloader">
    <img width="1" height="1" src="<?php echo $this->getSkinUrl('images/bg-drop.png') ?>" alt="" />
    <img width="1" height="1" src="<?php echo $this->getSkinUrl('images/bg-drop-top.png') ?>" alt="" />
</div>
<div class="nav-container">
    <ul id="nav">
        <?php echo $_menu ?>
    </ul>
</div>
<?php endif ?>