<?php
/* @var $this Mage_Catalog_Block_Product_List_Related */
?>
<?php if($this->getItems()->getSize()): ?>
<div class="block block-related">
    <div class="block-title">
        <strong><span><?php echo $this->__('Related Products') ?></span></strong>
    </div>
    <div class="block-content">
        <ol class="mini-products-list" id="block-related">
        <?php foreach($this->getItems() as $_item): ?>
            <li class="item">
                <div class="product">
                    <a href="<?php echo $_item->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_item->getName()) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(120, 80) ?>" width="120" height="80" alt="<?php echo $this->htmlEscape($_item->getName()) ?>" /></a>
                    <div class="product-details">
                        <?php
                        //TODO: move product ribbons to external template file
//                        $_link_start = '<a href="' . $_item->getProductUrl() . '" class="iceau-product-mark-link">';
//                        $_link_end = '</a>';
//
//                        /* @var $_iceau_helper VenProject_IceAU_Helper_Data */
//                        $_iceau_helper = Mage::helper("venproject_iceau");
//                        $_ribbons = $_iceau_helper->getProductRibbons($_item);
//
//                        if ($_ribbons['clearance']) {
//                            echo $_link_start . '<span class="iceau-product-mark iceau-product-mark-clearance">' . $this->__('Product has Clearance tag') . '</span>' . $_link_end;
//                        } elseif ($_ribbons['sale']) {
//                            echo $_link_start . '<span class="iceau-product-mark iceau-product-mark-sale">' . $this->__('Product has Sale tag') . '</span>' . $_link_end;
//                        } elseif ($_ribbons['new']) {
//                            echo $_link_start . '<span class="iceau-product-mark iceau-product-mark-new">' . $this->__('Product has New tag') . '</span>' . $_link_end;
//                        }
                        ?>
                        <p class="product-name product-name-wrap"><a href="<?php echo $_item->getProductUrl() ?>"><?php echo $this->htmlEscape($_item->getName()) ?></a></p>

                        <?php echo $this->getPriceHtml($_item, true, '-related') ?>

                        <?php if($_item->getIceauVideoUrl() != null): ?>
                            <a href="<?php echo $_item->getProductUrl(); ?>#video" class="video-icon"> <span><?php echo $this->__('Video Available'); ?></span></a>
                        <?php endif; ?>
                    </div>
                </div>
            </li>
        <?php endforeach ?>
        </ol>
        <script type="text/javascript">
            decorateList('block-related', 'none-recursive');

            document.observe('dom:loaded', function () {
                $$('p.product-name-wrap a').each(function(item) {
                    item.innerHTML = item.innerHTML.truncate(105, "...");
                });

                if (navigator.userAgent.match(/(iPad|iPhone|iPod)/i)) {
                    $$('.video-icon').invoke('hide');
                }
            });
        </script>
    </div>
</div>
<?php endif ?>
