<?php
/* @var $this Mage_Catalog_Block_Product_List_Upsell */
?>
<?php if(count($this->getItemCollection()->getItems())): ?>
<div class="box-collateral box-up-sell">
    <h2><?php echo $this->__('You may also be interested in the following product(s)') ?></h2>
    <table class="products-grid" id="upsell-product-table">
    <?php // $this->setColumnCount(5); // uncomment this line if you want to have another number of columns. also can be changed in layout ?>
    <?php $this->resetItemsIterator() ?>
    <?php for($_i=0;$_i<$this->getRowCount();$_i++): ?>
        <tr>
        <?php for($_j=0;$_j<$this->getColumnCount();$_j++): ?>
            <?php if($_link=$this->getIterableItem()): ?>
            <td>
                <a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_link->getName()) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_link, 'small_image')->resize(180, 120) ?>" width="180" height="120" alt="<?php echo $this->htmlEscape($_link->getName()) ?>" /></a>
                <?php
                //TODO: move product ribbons to external template file
//                $_link_start = '<a href="' . $_link->getProductUrl() . '" class="iceau-product-mark-link">';
//                $_link_end = '</a>';
//
//                /* @var $_iceau_helper VenProject_IceAU_Helper_Data */
//                $_iceau_helper = Mage::helper("venproject_iceau");
//                $_ribbons = $_iceau_helper->getProductRibbons($_link);
//
//                if ($_ribbons['clearance']) {
//                    echo $_link_start . '<span class="iceau-product-mark iceau-product-mark-clearance">' . $this->__('Product has Clearance tag') . '</span>' . $_link_end;
//                } elseif ($_ribbons['sale']) {
//                    echo $_link_start . '<span class="iceau-product-mark iceau-product-mark-sale">' . $this->__('Product has Sale tag') . '</span>' . $_link_end;
//                } elseif ($_ribbons['new']) {
//                    echo $_link_start . '<span class="iceau-product-mark iceau-product-mark-new">' . $this->__('Product has New tag') . '</span>' . $_link_end;
//                } else {
//                    echo '<div class="iceau-product-mark">&nbsp;</div>';
//                }
                ?>
                <h3 class="product-name product-name-wrap"><a href="<?php echo $_link->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_link->getName()) ?>"><?php echo $this->htmlEscape($_link->getName()) ?></a></h3>
                <?php echo $this->getPriceHtml($_link, true, '-upsell') ?>

                <?php if($_link->getIceauVideoUrl() != null): ?>
                    <a href="<?php echo $_link->getProductUrl(); ?>#video" class="video-icon"> <span><?php echo $this->__('Video Available'); ?></span></a>
                <?php endif; ?>

                <?php echo $this->getReviewsSummaryHtml($_link) ?>
            </td>
            <?php else: ?>
            <td class="empty">&nbsp;</td>
            <?php endif; ?>
        <?php endfor; ?>
        </tr>
    <?php endfor; ?>
    </table>
    <script type="text/javascript">
        decorateTable('upsell-product-table');

        document.observe('dom:loaded', function () {
            $$('p.product-name-wrap a').each(function(item) {
                item.innerHTML = item.innerHTML.truncate(105, "...");
            });

            if (navigator.userAgent.match(/(iPad|iPhone|iPod)/i)) {
                $$('.video-icon').invoke('hide');
            }
        });
    </script>
</div>
<?php endif ?>
