<?php
	$_order = $this->getOrder(); 
?>
<div class="section active allow order-confirm-create-account">
	<div class="step-title">
		<h2>Instantly Create an Ice.com Account
			<span class="required">* Required</span>
		</h2>
	</div>
	<div class="step-inner-wrap">
		<strong>Create an account and get:</strong>
		<p class="order-confirm-account-value-adds">
			<span>Exclusive discounts and rewards</span>
			<span>Faster Checkout</span>
			<span>Order tracking and purchase history</span>
		</p>

    <?php echo $this->getChildHtml('form_fields_before')?>
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="form-validate" class="inline-form">
        <div class="fieldset">
            <input type="hidden" name="success_url" value="<?php echo Mage::helper('customer')->getAccountUrl(); ?>" />
            <input type="hidden" name="error_url" value="<?php echo $this->getErrorUrl() ?>" />
            <input type="hidden" id="firstname" name="firstname" value="<?php echo $this->escapeHtml($_order->getBillingAddress()->getFirstname()) ?>" title="firstname" />

            <input type="hidden" id="lastname" name="lastname" value="<?php echo $this->escapeHtml($_order->getBillingAddress()->getLastname()) ?>" title="<?php echo $this->getStoreLabel('lastname') ?>"  />

            <ul class="form-list">
                <li class="fields">
                    <label for="email_address" class="required"><?php echo $this->__('Email Address') ?><em>*</em></label>
                    <div class="input-box">
                        <input type="text" name="email" id="email_address" value="<?php echo $this->escapeHtml($this->getOrder()->getBillingAddress()->getEmail()) ?>" title="<?php echo $this->__('Email Address') ?>" class="input-text validate-email required-entry" />
                    </div>
                </li>
            <?php $_dob = $this->getLayout()->createBlock('customer/widget_dob') ?>
            <?php if ($_dob->isEnabled()): ?>
                <li><?php echo $_dob->setDate($this->getFormData()->getDob())->toHtml() ?></li>
            <?php endif ?>
            <?php $_taxvat = $this->getLayout()->createBlock('customer/widget_taxvat') ?>
            <?php if ($_taxvat->isEnabled()): ?>
                <li><?php echo $_taxvat->setTaxvat($this->getFormData()->getTaxvat())->toHtml() ?></li>
            <?php endif ?>
            <?php $_gender = $this->getLayout()->createBlock('customer/widget_gender') ?>
            <?php if ($_gender->isEnabled()): ?>
                <li><?php echo $_gender->setGender($this->getFormData()->getGender())->toHtml() ?></li>
            <?php endif ?>
            </ul>

            <ul class="form-list">
	            <li class="fields">
	                <label for="password" class="required"><?php echo $this->__('Password') ?><em>*</em></label>
	                <div class="input-box">
	                    <input type="password" name="password" id="password" title="<?php echo $this->__('Password') ?>" class="input-text required-entry validate-password" placeholder="Password" />
	                </div>
	            </li>
              <li class="fields">
                  <label for="confirmation" class="required"><?php echo $this->__('Confirm Password') ?><em>*</em></label>
                  <div class="input-box">
                      <input type="password" name="confirmation" title="<?php echo $this->__('Confirm Password') ?>" id="confirmation" class="input-text required-entry validate-cpassword" placeholder="Confirm Password" />
                  </div>
              </li>
                <?php echo $this->getChildHtml('form.additional.info'); ?>
                <?php echo $this->getChildHtml('persistent.remember.me'); ?>
              <li class="control">
              		<label>&nbsp;</label>
                  <label for="is_subscribed">
                  	<input type="checkbox" name="is_subscribed" title="<?php echo $this->__('Sign Up for Newsletter') ?>" value="1" id="is_subscribed" checked="checked" class="checkbox" />
                  	<?php echo $this->__('Yes, send me exclusive email offers from Ice.') ?>
                  </label>
              </li>

              <li class="fields">
								<label>&nbsp;</label>
		            <button type="submit" title="<?php echo $this->__('Submit') ?>" class="button primary-button button-register">
		            	<span><?php echo $this->__('Create Account') ?></span>
		            </button>
              </li>
            </ul>
            <?php echo $this->getChildHtml('persistent.remember.me.tooltip'); ?>
        </div>
        <?php if (Mage::helper('checkout')->isContextCheckout()): ?>
            <input name="context" type="hidden" value="checkout" />
        <?php endif; ?>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var dataForm = new VarienForm('form-validate', true);
        <?php if($this->getShowAddressFields()): ?>
        new RegionUpdater('country', 'region', 'region_id', <?php echo $this->helper('directory')->getRegionJson() ?>, undefined, 'zip');
        <?php endif; ?>
    //]]>
    </script>
	</div>
</div>