<?php
/**
 * Product view template
 *
 * @see Mage_Catalog_Block_Product_View
 * @see Mage_Review_Block_Product_View
 */
?>
<?php $_helper  = $this->helper('catalog/output'); ?>
<?php $_product = $this->getProduct(); ?>
<script type="text/javascript">
    var optionsPrice = new Product.OptionsPrice(<?php echo $this->getJsonConfig() ?>);
</script>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<div class="product-view">
    <div class="product-essential">
    <form action="<?php echo $this->getSubmitUrl($_product) ?>" method="post" id="product_addtocart_form"<?php if($_product->getOptions()): ?> enctype="multipart/form-data"<?php endif; ?>>
        <div class="no-display">
            <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
            <input type="hidden" name="related_product" id="related-products-field" value="" />
        </div>

        <div class="product-shop">
            <div class="product-name">
                <h1><?php echo $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h1>
            </div>

            <?php echo $this->getReviewsSummaryHtml($_product, false, true)?>
            <?php echo $this->getTierPriceHtml() ?>
            <?php echo $this->getChildHtml('extrahint') ?>
            <?php echo $this->getChildHtml('product_type_data') ?>

            <div class="price-save-persent">
                <?php $_finalPrice = $this->helper('tax')->getPrice($_product, $_product->getFinalPrice()) ?>
                <?php $_priceMultiplier = Mage::helper('pricemultiplier/data')->getPriceMultiplier() ?>
                <?php $_msrp = ($_product->getMsrp()) ? $_product->getMsrp() : ($_product->getPrice() * $_priceMultiplier); ?>
                <?php $_regularPrice = $this->helper('tax')->getPrice($_product, $_msrp); ?>

                <?php $_savingPercent = round((($_regularPrice-$_finalPrice)/$_regularPrice)*100,1); ?>
                <?php echo ($_savingPercent>0) ? $this->__("You save %s%%", $_savingPercent) : ""; ?>
            </div>
            <p class="product-description short-description"><?php echo $_product->getShortDescription() ?></p>
            <?php echo $this->getChildHtml('alert_urls') ?>

            <?php if (!$_product->isSaleable()): ?>
                <div class="hr"> </div>
                <p class="sold-out-button-wrapper"><span class="sold-out-button-disable"><?php echo $this->__("Sold Out"); ?></span></p>
            <?php endif; ?>

            <?php if (!$_product->isAvailable()): ?>
                <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
            <?php elseif($_product->isAvailable()): ?>

                <?php $_productQty = $_product->getStockItem()->getStockQty(); ?>
                <?php $_qtyThreshold = Mage::getStoreConfig('cataloginventory/options/stock_threshold_qty'); ?>
                <?php if ($_productQty > 0 && $_productQty <= $_qtyThreshold) : ?>
                    <p class="availability in-stock"><span><?php echo $this->__('Only %s left', $_productQty) ?></span></p>
                <?php else: ?>
                    <p class="availability in-stock"><span><?php echo $this->__('In stock') ?></span></p>
                <?php endif; ?>
            <?php else: ?>
                <p class="availability out-of-stock"><span><?php echo $this->__('Out of stock') ?></span></p>
            <?php endif; ?>


            <?php if (!$this->hasOptions()):?>
                <div class="add-to-box">
                    <?php echo $this->getChildHtml('addtocart') ?>
                </div>
                <?php echo $this->getChildHtml('extra_buttons') ?>
            <?php endif; ?>

            <?php echo $this->getChildHtml('other');?>

            <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
            <?php endif;?>
        </div>

        <div class="product-img-box">
            <?php echo $this->getChildHtml('media') ?>
        </div>
        <div class="product-options-wrap">
            <?php if ($_product->isSaleable() && $this->hasOptions()):?>
                <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
            <?php endif;?>
        </div>

        <div class="clearer"></div>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var productAddToCartForm = new VarienForm('product_addtocart_form');
        productAddToCartForm.submit = function(button, url) {
            if (this.validator.validate()) {
                var form = this.form;
                var oldUrl = form.action;

                if (url) {
                   form.action = url;
                }
                var e = null;
                try {
                    this.form.submit();
                } catch (e) {
                }
                this.form.action = oldUrl;
                if (e) {
                    throw e;
                }

                if (button && button != 'undefined') {
                    button.disabled = true;
                }
            }
        }.bind(productAddToCartForm);

        productAddToCartForm.submitLight = function(button, url){
            if(this.validator) {
                var nv = Validation.methods;
                delete Validation.methods['required-entry'];
                delete Validation.methods['validate-one-required'];
                delete Validation.methods['validate-one-required-by-name'];
                // Remove custom datetime validators
                for (var methodName in Validation.methods) {
                    if (methodName.match(/^validate-datetime-.*/i)) {
                        delete Validation.methods[methodName];
                    }
                }

                if (this.validator.validate()) {
                    if (url) {
                        this.form.action = url;
                    }
                    this.form.submit();
                }
                Object.extend(Validation.methods, nv);
            }
        }.bind(productAddToCartForm);
    //]]>
    </script>
    </div>

    <div class="product-collateral">
<?php foreach ($this->getChildGroup('detailed_info', 'getChildHtml') as $alias => $html):?>
        <div class="iceau-tabs box-collateral <?php echo "box-{$alias}"?>">
            <?php if ($title = $this->getChildData($alias, 'title')):?>
            <h2><?php echo $this->escapeHtml($title); ?></h2>
            <?php endif;?>
            <?php echo $html; ?>
        </div>
<?php endforeach;?>
        <?php echo $this->getChildHtml('product_additional_data') ?>
    </div>
</div>