<?php
/**
 * Product additional attributes template
 *
 * @see Mage_Catalog_Block_Product_View_Attributes
 */
?>
<?php /* @var $this Mage_Catalog_Block_Product_View_Attributes */ ?>
<?php
    $_helper = $this->helper('catalog/output');
    $_product = $this->getProduct();
?>
<?php if($_additional = $this->getAdditionalData()): ?>
    <?php
    $codeAttributes       = array_keys($_additional);
    $first_attribute_code = reset($codeAttributes);
    if (strpos($first_attribute_code, 'iceus_watch_type') === 0): ?>
        <table class="data-table product-attribute-table" id="product-attribute-stones-table">
            <col width="25%" />
            <col />
            <tbody>
            <?php $i = 0; ?>
            <?php foreach ($_additional as $_data): ?>
                <?php if ($i == 0): ?>
                    <tr>
                        <th class="label" colspan="2"><?php echo $_helper->productAttribute($_product, $_data['value'], $_data['code']) ?>:</th>
                    </tr>
                <?php else: ?>
                    <tr>
                        <th class="label"><?php echo $this->escapeHtml($this->__($_data['label'])) ?></th>
                        <td class="data"><?php echo $_helper->productAttribute($_product, $_data['value'], $_data['code']) ?></td>
                    </tr>
                <?php endif; ?>
                <?php $i++; ?>
            <?php endforeach; ?>
            <?php if ($i < 2): ?>
                </tr>
            <?php endif; ?>
            </tbody>
        </table>
        <script type="text/javascript">decorateTable('product-attribute-specs-table')</script>
    <?php endif; ?>
<?php endif; ?>
