<?php
/* @var $this Mage_Catalog_Block_Product_List_Upsell */
$_productCollection = $this->getItemCollection()->getItems();
$_helper            = $this->helper('catalog/output');
?>

<?php if(count($_productCollection)): ?>
<div class="box-collateral box-up-sell">
    <h3 class="tab-heading"><?php echo $this->__('You may also be interested in the following product(s)') ?></h3>
    
    <ul class="products-grid">
    <?php $this->resetItemsIterator() ?>
    <?php for($_i=0;$_i<$this->getRowCount();$_i++): ?>
        <ul class="products-grid">       
       <?php for($_j=0;$_j<$this->getColumnCount();$_j++): ?>
            <?php if($_product = $this->getIterableItem()): ?>
            <li class="item">
                <?php // Product Image ?>
                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135); ?>" width="135" height="135" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /></a>
                <?php // Product description ?>
                <div>
                    <div>
                        <?php $_productNameStripped = $this->stripTags($_product->getName(), null, true); ?>
                        <h3 class="product-name">
                            <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $_productNameStripped; ?>">
                                <?php echo $_helper->productAttribute($_product, $_product->getName() , 'name'); ?>
                            </a>
                        </h3>
                        <?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
                        <?php echo $this->getChild('product_list_price')->setData('product', $_product)->toHtml(); ?>
                        <ul class="add-to-links">
                            <?php if ($this->helper('wishlist')->isAllow()) : ?>
                                <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php echo $this->__('Add to Wishlist') ?></a></li>
                            <?php endif; ?>
                            <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                                <li><span class="separator">|</span> <a href="<?php echo $_compareUrl ?>" class="link-compare"><?php echo $this->__('Add to Compare') ?></a></li>
                            <?php endif; ?>
                        </ul>
                    </div>
                </div>
            </li>
            <?php endif; ?>
       <?php endfor; ?>
       </ul>

    <?php endfor; ?>
    <script type="text/javascript">
        decorateTable('upsell-product-table');

        document.observe('dom:loaded', function () {
            $$('p.product-name-wrap a').each(function(item) {
                item.innerHTML = item.innerHTML.truncate(105, "...");
            });

            if (navigator.userAgent.match(/(iPad|iPhone|iPod)/i)) {
                $$('.video-icon').invoke('hide');
            }
        });
    </script>
</div>
<?php endif ?>
