<?php /* @var $this Ven_Content_Block_Category_View */ ?>
<?php /* @var $this Mage_Catalog_Block_Category_View */ ?>
<?php
/**
 * Category view template
 *
 * @see Mage_Catalog_Block_Category_View
 */
?>
<?php
    $_helper    = $this->helper('catalog/output');
    $_category  = $this->getCurrentCategory();
    $_imgHtml   = '';
    if ($_imgUrl = $_category->getImageUrl()) {

        // changing url link of image into directory link
        $dirImg = Mage::getBaseDir() . str_replace("/", DS, strstr($_imgUrl, '/media'));

        $_imageSizeWidth  = 0;
        $_imageSizeHeight = 0;

        if (file_exists($dirImg)) {
            $imageObj         = new Varien_Image($dirImg);
            $_imageSizeWidth  = $imageObj->getOriginalWidth();
            $_imageSizeHeight = $imageObj->getOriginalHeight();
        }

        $_imageSizeWidth  = ($_imageSizeWidth  > 0) ? " width='{$_imageSizeWidth}'"   : "";
        $_imageSizeHeight = ($_imageSizeHeight > 0) ? " height='{$_imageSizeHeight}'" : "";

        $_imgHtml = '<p class="category-image"><img src="' . $_imgUrl . '" ' . $_imageSizeWidth . ' ' . $_imageSizeHeight . ' alt="' . $this->htmlEscape($_category->getName()) . '" title="' . $this->htmlEscape($_category->getName()) . '" /></p>';
        $_imgHtml = $_helper->categoryAttribute($_category, $_imgHtml, 'image');
    }
?>

<div class="category-title-wrapper">
    <?php if($_imgUrl): ?>
        <?php echo $_imgHtml ?>
    <?php endif; ?>

    <div class="page-title category-title">
        <?php if($this->IsRssCatalogEnable() && $this->IsTopCategory()): ?>
            <a href="<?php echo $this->getRssLink() ?>" class="link-rss"><?php echo $this->__('Subscribe to RSS Feed') ?></a>
        <?php endif; ?>
        <h1<?php if ($_category->getData('iceau_page_title_hide')): ?> class="image-title"<?php endif; ?>><?php echo $_helper->categoryAttribute($_category, $_category->getName(), 'name') ?></h1>
    </div>
</div>

<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>

<?php if($this->isContentMode()): ?>
    <?php echo $this->getCmsBlockHtml() ?>

<?php elseif($this->isMixedMode()): ?>
    <?php echo $this->getCmsBlockHtml() ?>
    <?php echo $this->getProductListHtml() ?>

<?php else: ?>
    <?php echo $this->getProductListHtml() ?>
<?php endif; ?>

<?php if($_description=$this->getCurrentCategory()->getDescription()): ?>
<div class="category-description std">
    <?php echo $_helper->categoryAttribute($_category, $_description, 'description') ?>
</div>
<?php endif; ?>
